### ISSUE TITLE
Upstream `directories` has been archived and possibly unmaintained again

### ISSUE THREAD

**Issue by Aloso** [xdg-rs/dirs#34] opened 2020-07-19 20:35 UTC
It looks to me like the [`directories` crate](https://github.com/dirs-dev/directories-rs) is no longer unmaintained; there are new commits on March 4, June 21 and July 4, including a new major version release. I guess the README should be updated to reflect this.

**Comment by Ralith** [comment] 2020-09-08 19:33
Ironically, that makes for more recent maintenance than this crate now has. Is this effort still useful?

**Comment by Dylan-DPC** [comment] 2020-09-08 22:40
Yes. We have already committed to maintaining this and we can't go back on this. We will most likely keep things on par with the original crate, so most changes that are made there will reflect here unless we decide to diverge (we don't see a good reason to do that at the moment)

**Comment by lzutao** [comment] 2020-10-13 05:03
Wow, don't know what the problem is.
![image](https://user-images.githubusercontent.com/15225902/95817612-14a58700-0d4c-11eb-96fe-556e106f839c.png)

**Comment by lzutao** [comment] 2021-01-05 02:06
Hm, Simon changed his thoughts and unarchived crates:
![image](https://user-images.githubusercontent.com/15225902/103598460-3c644f80-4f35-11eb-9787-49051d685b26.png)

Let's close this issue as such. Still I don't know what can we do in these cases.

**Closed by lzutao** 2021-01-05 02:07 UTC
Labels: A-docs, C-question, I-needs-decision, P-low
